
localrules: make_bamlists

include: "rules/common.smk"


rule all:
  input:
    safs=ALLBAT
    
rule index_fasta:
  input:
    genome=config["genome"]
  output:
    fai=config["genome"] + ".fai"
  log:
    "results/logs/index-fasta/log.txt"
  conda:
    "envs/samtools.yaml"
  benchmark:
    "results/benchmarks/index_fasta/log.txt"
  shell:
    " samtools faidx {input.genome} 2> {log}"



rule make_bamlists:
  input:
    bl=get_bams_in_batch
  output:
    bl="results/{mode}/{chunk}/bamlists/{bat}.txt"
  log:
    "results/logs/make_bamlists/{mode}/{chunk}/{bat}.txt"
  benchmark:
    "results/benchmarks/make_bamlists/{mode}/{chunk}/{bat}.txt"
  shell:
    "echo {input.bl} | awk '{{for(i=1;i<=NF;i++) print $i}}' > {output.b1} 2> {log} "
    
    

rule calc_saf:
  input:
    genome=config["genome"],
    fai=config["genome"] + ".fai",
    bl="results/{mode}/{chunk}/bamlists/{bat}.txt"
  output:
    saf="results/{mode}/{chunk}/saf/{bat}.saf.idx"
  params:
    bf=config["params"]["angsd_bam_filters"],
    cs=config["params"]["calc_saf"],
    chunk_opt=get_chunk
  threads: 1
  conda:
    "envs/angsd.yaml"
  log:
    "results/logs/calc_saf/{mode}/{chunk}/{bat}.txt"
  benchmark:
    "results/becnhmarks/calc_saf/{mode}/{chunk}/{bat}.txt"
  shell:
    " PREFIX=$(echo {output.saf} | sed 's/\.saf\.idx$//g;');"
    " angsd -b {input.bl} -nThreads {threads} -anc {input.genome} {params.chunk_opt} "
    " -ref {input.genome} -out $PREFIX {params.cs} {params.bf} > {log} 2>&1 "
    
    

